### ISSUE TITLE
"Rounded Mplus 1c"が使えない状態です

### ISSUE THREAD

**Issue by t--takai** [qrac/yakuhanjp#22]
# 報告

Yakuhanjpデモページと同じようにフォントが丸くならないな、  
（カッコなどは丸くなった）と思ってイジってみたところ。

```
font-family: "Rounded Mplus 1c";
```

を指定する場合

scssファイルなどに以下を記載しなければならないようです。

```
@import url(https://fonts.googleapis.com/earlyaccess/roundedmplus1c.css);
```

## 対策

という状態なので、以下のいずれかを行っていただけると助かります。

- googleのフォントもimportするようにドキュメントの修正
- YakuhanRPの修正

***

以上となりますので、まずは僕と同じ状態になるのかを
ご確認よろしくお願いします。

**Comment by qrac** [comment]
共有ありがとうございます！

そうですね。同じ状態になります。
約物のみをオーバーライドするフォントですので、仕様上間違いではありません。
私も、丸文字を使う場合は貼っていただいた `earlyaccess/roundedmplus1c.css` を併用しています。

YakuHanRP側で併用するフォントを縛ることは行いませんが、
派生ライブラリで「これ読み込めばOK」みたいなものを作るのはアリだと思いました！

**Comment by qrac** [comment]
もしくは別CSSファイル（おすすめ丸文字セット）として同封。

**Comment by t--takai** [comment]
すみません、重要なところを読み飛ばしていたようですmm

NotoSansをベースにしているから、NotoSansを改変したのものだと勘違いしておりました。

> 派生ライブラリで「これ読み込めばOK」みたいなものを作る

気が向いたらやって欲しいです

いやー本当に申し訳ないです。
