### ISSUE TITLE
unicode-rangeをCSSに含めてほしい

### ISSUE THREAD

**Issue by tamaina** [qrac/yakuhanjp#29]
## Summary
`@font-face`に`unicode-range`が記載されていないと、ブラウザは指定されたフォントファイルに含まれる文字を確認するために必ずフォントファイルをダウンロードし、再描画します。  
`unicode-range`を記載するとダウンロードを待つことなく`font-family`に次に指定されたフォントの処理に移れるうえ再描画がなくなるため、Webページのパフォーマンスが若干向上します。  
ご検討ください。

Off topic: #21 もご再考ください。

### YakuHanJP & YakuHanRP （25文字）
u+3001-3002, u+3008-3011, u+3014-3015, u+30fb, u+ff01, u+ff08-ff09, u+ff1a-ff1b, u+ff1f, u+ff3b, u+ff3d, u+ff5b, u+ff5d  
、。！？〈〉《》「」『』【】〔〕・（）：；［］｛｝

### YakuHanJPs & YakuHanRPs （18文字）
u+3008-3011, u+3014-3015, u+ff08-ff09, u+ff3b, u+ff3d, u+ff5b, u+ff5d  
〈〉《》「」『』【】〔〕（）［］｛｝

### YakuHanMP （23文字）
u+3001-3002, u+300a-3011, u+3014-3015, u+30fb, u+ff01, u+ff08-ff09, u+ff1a-ff1b, u+ff1f, u+ff3b, u+ff3d, u+ff5b, u+ff5d  
、。！？《》「」『』【】〔〕・（）：；［］｛｝

### YakuHanMPs （16文字）
u+300a-3011, u+3014-3015, u+ff08-ff09, u+ff3b, u+ff3d, u+ff5b, u+ff5d  
《》「」『』【】〔〕（）［］｛｝

**Comment by qrac** [comment]
@tamaina それは素晴らしいですね！試してみます。

**Comment by qrac** [comment]
@tamaina 早速、v3.3.0にて対応しました！ご提案ありがとうございます！
