### ISSUE TITLE
全角カンマ・ピリオドへの対応

### ISSUE THREAD

**Issue by natrium11321** [qrac/yakuhanjp#32]
論文などの科学技術文章では，和文でも読点「、」句点「。」より全角カンマ「，」全角ピリオド「．」が好まれて使用される傾向にあり，これらの文字も半角にする対象の約物として追加していただけると嬉しいです．ご検討いただけると幸いです．

**Comment by qrac** [comment]
@natrium11321 ご提案ありがとうございます！

以下は、CSSの `font-feature-settings: "halt"` を用いてみた例です。期待されているイメージと合っていますか？

![image](https://user-images.githubusercontent.com/9658016/73132441-9cccea80-405e-11ea-89f7-46987d419cd2.png)

[YakuHanJP - Issues #32](https://codepen.io/qrac/full/VwYRVdV)

論文であれば、積めない方が読みやすい気もしますが、いかがでしょうか？

**Comment by natrium11321** [comment]
@quac ありがとうございます．まさにそのようなイメージです．論文 (PDF) のフォントとして直接用いるわけではなく，科学技術系の web ページで使用したいと思っています．

**Comment by qrac** [comment]
@natrium11321 あ、なるほど。理工系文章で書くwebページの装飾という用途ですね。

以下の通り、YakuHanJP EX（特別版）の一部としてリリースしました！

![image](https://user-images.githubusercontent.com/9658016/73161944-010baf00-4130-11ea-948d-a66073396c1a.png)

[YakuHanJP EX Science](https://codepen.io/qrac/full/BayENGO)

次のURLをwebサイトに貼って、YakuHanJPを指定すれば使えます👍

```html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/yakuhanjp-ex@0.3.0/dist/css/yakuhanjp-ex-science.min.css"/>
```

```css
.yakuhanjp {
  font-family: YakuHanJP, "Hiragino Sans", Meiryo, "Yu Gothic Medium", sans-serif;
}
```

通常のweb制作では使う頻度が低そうなので、YakuHanJP本体への追加は見送りますが、理工系文章のwebデザインの文字を詰める観点としてはありだと思いました。

よろしくお願いします！

**Comment by natrium11321** [comment]
@qrac おおお，手元で試してみましたがかなりいい感じです！早速のご対応ありがとうございます！！大変助かりました！

**Comment by qrac** [comment]
@natrium11321 いえいえ！ご提案ありがとうございました！！
