### ISSUE TITLE
mergedされたフォントをインストールすると文字がおかしい

### ISSUE THREAD

**Issue by Aspc-Nakai** [qrac/yakuhanjp#74]
![issues](https://github.com/qrac/yakuhanjp/assets/112994553/04b3d6a0-bc09-40d1-9f08-f860a317efee)

packages > maerged  > YakuHanJP　> otf 
配下以下のフォントをwindowsで開くとバグっている表示になります。（添付）

packages > core >   > YakuHanJP　> otf 
配下のフォントはフォントの形が違ってみえます。

インストールすべきフォントはどれでしょうか。

**Comment by qrac** [comment]
@Aspc-Nakai 
ご報告ありがとうございます！
インストールして使うフォントは `packages > merged > YakuHanJP > otf` で間違いありませんが、確かにWindowsだと表示が変になる場合がありますね。
原因を特定して、フォント側で直せる問題であれば修正して公開いたします。

**Comment by qrac** [comment]
### 調査結果

元フォントのNoto Sans JPがVariable Fontsベースになったことが原因

- レンダリング時にパスを結合できないソフトウェアは抜きのアウトラインが発生
- Google Fontsでは他にもVariable FontsベースになったフォントがありそれぞれIssuesが上がっている
  - [Issue when using -webkit-text-stroke · Issue #292 · rsms/inter](https://github.com/rsms/inter/issues/292)
  - [Montserrat and -webkit-text-stroke overlapping · Issue #4212 · google/fonts](https://github.com/google/fonts/issues/4212)
- ブラウザのCSS（text-stroke）・MacのSketch（Figmaなどは大丈夫らしい）にも影響
- Noto Sans JPはVariable Fontsベースになった2022年のバージョンから影響が出ている様子
  - [Noto Sans JP 2.004 by simoncozens · Pull Request #4590 · google/fonts](https://github.com/google/fonts/pull/4590)
  - [Noto Sans JP: Version 2.004-H2 added by simoncozens · Pull Request #5469 · google/fonts](https://github.com/google/fonts/pull/5469)
  - [noto sans text-stroke lang:ja - 検索 / X](https://twitter.com/search?q=noto%20sans%20text-stroke%20lang%3Aja&src=typed_query&f=live)

### 試したもの

| YakuHanJP v4.0.0 > MergedYakuHanJP-Black.otf > Windowsメモパッド（文字サイズによっては崩れない） |
| --- |
| ![スクリーンショット 2023-11-22 175303](https://github.com/qrac/yakuhanjp/assets/9658016/80e6ace4-3622-4255-b97f-2da0329bee2c) |

| Noto Sans JP | Noto Serif JP（不具合なし） | M PLUS Rounded 1c（不具合なし） |
| --- | --- | --- |
| ![fonts google com_noto_specimen_Noto+Sans+JP_query=notoのコピー](https://github.com/qrac/yakuhanjp/assets/9658016/c7922866-5bb8-45be-b81e-92fc109816dc) | ![fonts google com_noto_specimen_Noto+Sans+JP_query=noto](https://github.com/qrac/yakuhanjp/assets/9658016/afa51529-f8a2-4cc4-b20e-67952bd91086) | ![fonts google com_](https://github.com/qrac/yakuhanjp/assets/9658016/92ba2dd5-ef09-43e0-9628-0761697346b3) |

### 対策案

- パスを結合したファイルを配信する（表示側で対処できることはないため）

### 懸念点

- Git上のファイル容量が1種類につき30MB近く増える計算
- オプション「重なったパスを合体」の付与？ > 全ファイル生成し直し（Noto Sans JPマージ系のみで良いのか）
- TTF形式を追加するだけで良いのか？ > Windowsで試す

**Comment by qrac** [comment]
@Aspc-Nakai 
v4.0.1でTTF形式のマージフォントを追加しましたので、以下のディレクトリからダウンロードして試してみてください。

- https://github.com/qrac/yakuhanjp/tree/main/packages/merged/YakuHanJP/ttf

![スクリーンショット 2023-11-26 114351](https://github.com/qrac/yakuhanjp/assets/9658016/b4478fc3-3603-4612-ae75-f0ab8d25c39d)

**Comment by Aspc-Nakai** [comment]
@qrac 
ありがとうございます。
windowsはOpenFontのみインストールできるので
otfファイルで検証させていただけないでしょうか。。。

**Comment by qrac** [comment]
@qrac 
Windows 11でttfファイルのインストールは検証済みなのですが、他に何か問題がありそうですか？

**Comment by Aspc-Nakai** [comment]
@qrac 
![issue](https://github.com/qrac/yakuhanjp/assets/112994553/5a255b8f-450a-450b-bcab-34c847b675d1)

windows10、macbook M1で検証した結果
win > 有効なフォントではありません
mac > インストール可能なフォントが選択されていません

と表示されます。。

**Comment by qrac** [comment]
@Aspc-Nakai 
フォントファイルの置き場所や権限の問題である可能性はないでしょうか？
例えば、MacのParallels DesktopでWindowsを使った場合、Mac上のディレクトリのフォントは開けませんが、仮想環境のCドライブ配下にフォントがある場合は開くことができます。

| 有効でないディレクトリ | 有効なディレクトリ |
| --- | --- |
| <img width="1680" alt="ScreenShot 2023-11-27 18 24 34" src="https://github.com/qrac/yakuhanjp/assets/9658016/a7884628-d860-4025-b464-92881ae4e4c1"> | <img width="1680" alt="ScreenShot 2023-11-27 18 25 15" src="https://github.com/qrac/yakuhanjp/assets/9658016/41d92bf4-7064-4197-85c8-8ac966c542c0"> |

**Comment by Aspc-Nakai** [comment]
@qrac 

確認できました！
ありがとうございました。
issueはcloseさせていただきます。
